(function(g){var window=this;var wGa=function(a,b){return g.Sb(a,b)},$5=function(a,b,c){a.C.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.kn(a.C,b,c)},xGa=function(a,b){var c=[];
g.bj(b,function(d){try{var e=g.Xn.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Wn(e)&&c.push(d)},a);
return c},yGa=function(a,b){var c=xGa(a,b);
g.Fb(c,function(d){g.Xn.prototype.remove.call(this,d)},a)},zGa=function(a){if(a.Md){if(a.Md.locationOverrideToken)return{locationOverrideToken:a.Md.locationOverrideToken};
if(null!=a.Md.latitudeE7&&null!=a.Md.longitudeE7)return{latitudeE7:a.Md.latitudeE7,longitudeE7:a.Md.longitudeE7}}return null},AGa=function(a,b){g.lb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},BGa=function(a,b){var c=b instanceof g.Ec?b:g.Kc(b,/^data:image\//i.test(b));
a.src=g.Fc(c)},d6=function(){},CGa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},DGa=function(a){if(a.Qe&&"function"==typeof a.Qe)return a.Qe();
if("string"===typeof a)return a.split("");if(g.Ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ob(a)},EGa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ra(a)||"string"===typeof a)g.Fb(a,b,void 0);else{if(a.eg&&"function"==typeof a.eg)var c=a.eg();else if(a.Qe&&"function"==typeof a.Qe)c=void 0;else if(g.Ra(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Pb(a);d=DGa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},FGa=function(a,b,c,d){var e=new g.Ym(null,void 0);
a&&g.Zm(e,a);b&&g.$m(e,b);c&&g.an(e,c);d&&(e.B=d);return e},e6=function(a,b){g.Ko[a]=!0;
var c=g.Io();c&&c.publish.apply(c,arguments);g.Ko[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Vm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",GGa(this,a.capabilities||""),HGa(this,a.experiments||""))},GGa=function(a,b){a.capabilities.clear();
g.Je(b.split(","),g.Va(wGa,IGa)).forEach(function(c){a.capabilities.add(c)})},HGa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},JGa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},KGa=function(a){return new g6(a)},LGa=function(a){return Array.isArray(a)?g.Oc(a,KGa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+g.Oc(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},MGa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.ib(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.ib(a,function(c){return h6(c,b)})},NGa=function(){var a=(0,g.kt)();
a&&yGa(a,a.u.hi(!0))},n6=function(){var a=g.nt("yt-remote-connected-devices")||[];
g.Bb(a);return a},OGa=function(a){if(g.nb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},PGa=function(a){g.mt("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.nt("yt-remote-device-id");a||(a=k6(),g.mt("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.lb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.lb(a,b);g.pt()&&g.Eb(a,b);a=OGa(a);if(g.nb(a))try{g.xq("remote_sid")}catch(c){}else try{g.vq("remote_sid",a.join(","),-1)}catch(c){}},QGa=function(){return g.nt("yt-remote-session-browser-channel")},RGa=function(){return g.nt("yt-remote-local-screens")||[]},SGa=function(){g.mt("yt-remote-lounge-token-expiration",!0,86400)},TGa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(RGa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.hh(c,function(d){return!g.lb(b,d)})&&SGa();
g.mt("yt-remote-local-screens",a,31536E3)},UGa=function(a,b){g.mt("yt-remote-session-browser-channel",a);
g.mt("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.lb(c,d)||c.push(d);PGa(c);q6()},r6=function(a){a||(g.ot("yt-remote-session-screen-id"),g.ot("yt-remote-session-video-id"));
q6();a=n6();g.qb(a,p6());PGa(a)},VGa=function(){if(!s6){var a=g.ho();
a&&(s6=new g.Rn(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},WGa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},XGa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?YGa(a.shift(),function(){t6(a)}):u6()},ZGa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},YGa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.id(d,g.lg(a));(document.head||document.documentElement).appendChild(d)},u6=function(){var a=XGa();
a&&a(!1,"No cast extension found")},aHa=function(){if($Ga){var a=2,b=XGa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;YGa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},bHa=function(){aHa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.Ee=b;this.F=(0,g.z)(this.rI,this);this.u=!1;this.B=0;this.C=this.Sa=null;this.D=[]},w6=function(a,b,c){g.B.call(this);
this.D=null!=c?a.bind(c):a;this.Ee=b;this.C=null;this.u=!1;this.B=0;this.Sa=null},x6=function(a){a.Sa=g.Tm(function(){a.Sa=null;
a.u&&!a.B&&(a.u=!1,x6(a))},a.Ee);
var b=a.C;a.C=null;a.D.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return CGa(a)},z6=function(){},A6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},C6=function(a){B6.dispatchEvent(new cHa(B6,a))},cHa=function(a){g.Kl.call(this,"statevent",a)},D6=function(){},dHa=function(){},fHa=function(a){return(a=eHa(a))?new ActiveXObject(a):new XMLHttpRequest},eHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},E6=function(a,b,c,d){this.u=a;
this.B=b;this.N=c;this.K=d||1;this.F=45E3;this.D=new g.V0(this);this.C=new g.Sm;this.C.setInterval(250)},hHa=function(a,b,c){a.un=1;
a.ij=a6(b.clone());a.Gl=c;a.I=!0;gHa(a,null)},F6=function(a,b,c,d,e){a.un=1;
a.ij=a6(b.clone());a.Gl=null;a.I=c;e&&(a.iF=!1);gHa(a,d)},gHa=function(a,b){a.mn=g.A();
G6(a);a.ek=a.ij.clone();b6(a.ek,"t",a.K);a.eq=0;a.Nd=a.u.av(a.u.Mp()?b:null);0<a.Rv&&(a.nt=new w6((0,g.z)(a.gG,a,a.Nd),a.Rv));a.D.ra(a.Nd,"readystatechange",a.OP);var c=a.Uk?g.Yb(a.Uk):{};a.Gl?(a.au="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nd.send(a.ek,a.au,a.Gl,c)):(a.au="GET",a.iF&&!g.ze&&(c.Connection="close"),a.Nd.send(a.ek,a.au,null,c));a.u.Vg(1)},kHa=function(a,b,c){for(var d=!0;!a.Ak&&a.eq<c.length;){var e=iHa(a,c);
if(e==H6){4==b&&(a.xj=4,C6(15),d=!1);break}else if(e==jHa){a.xj=4;C6(16);d=!1;break}else I6(a,e)}4==b&&0==c.length&&(a.xj=1,C6(17),d=!1);a.eh=a.eh&&d;d||(J6(a),K6(a))},iHa=function(a,b){var c=a.eq,d=b.indexOf("\n",c);
if(-1==d)return H6;c=Number(b.substring(c,d));if(isNaN(c))return jHa;d+=1;if(d+c>b.length)return H6;var e=b.substr(d,c);a.eq=d+c;return e},nHa=function(a,b){a.mn=g.A();
G6(a);var c=b?window.location.hostname:"";a.ek=a.ij.clone();$5(a.ek,"DOMAIN",c);$5(a.ek,"t",a.K);try{a.jh=new ActiveXObject("htmlfile")}catch(n){J6(a);a.xj=7;C6(22);K6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in L6)h=L6[h];else if(h in mHa)h=L6[h]=mHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
L6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.fd(g.jc("b/12014412"),d+"</body></html>");a.jh.open();a.jh.write(g.bd(c));a.jh.close();a.jh.parentWindow.m=(0,g.z)(a.cP,a);a.jh.parentWindow.d=(0,g.z)(a.hE,a,!0);a.jh.parentWindow.rpcClose=(0,g.z)(a.hE,a,!1);c=a.jh.createElement("DIV");a.jh.parentWindow.document.body.appendChild(c);d=g.Jc(a.ek.toString());d=g.md(g.Fc(d));d=g.fd(g.jc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,d);a.u.Vg(1)},G6=function(a){a.Fy=g.A()+a.F;
oHa(a,a.F)},oHa=function(a,b){if(null!=a.Bn)throw Error("WatchDog timer not null");
a.Bn=A6((0,g.z)(a.oP,a),b)},M6=function(a){a.Bn&&(g.v.clearTimeout(a.Bn),a.Bn=null)},K6=function(a){a.u.mB()||a.Ak||a.u.Dr(a)},J6=function(a){M6(a);
g.cg(a.nt);a.nt=null;a.C.stop();g.qAa(a.D);if(a.Nd){var b=a.Nd;a.Nd=null;b.abort();b.dispose()}a.jh&&(a.jh=null)},I6=function(a,b){try{a.u.ZD(a,b),a.u.Vg(4)}catch(c){}},qHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;pHa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){qHa(a,b,c,d,f)},f)})}},pHa=function(a,b,c){var d=new Image;
d.onload=function(){try{N6(d),c(!0)}catch(e){}};
d.onerror=function(){try{N6(d),c(!1)}catch(e){}};
d.onabort=function(){try{N6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{N6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
BGa(d,a)},N6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},O6=function(a){g.hm.call(this);
this.headers=new g.Vm;this.ba=a||null;this.B=!1;this.Y=this.u=null;this.oa=this.P="";this.I=0;this.D="";this.F=this.ha=this.N=this.fa=!1;this.K=0;this.V=null;this.za="";this.X=this.ea=!1},rHa=function(a){return g.xe&&g.Zd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},sHa=function(a){return"content-type"==a.toLowerCase()},uHa=function(a,b){a.B=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;tHa(a);P6(a)},tHa=function(a){a.fa||(a.fa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},wHa=function(a){if(a.B&&"undefined"!=typeof g.$0)if(a.Y[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.N&&4==Q6(a))g.Tm(a.VD,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.wd(1,String(a.P));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!vHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<Q6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";tHa(a)}}finally{P6(a)}}},P6=function(a,b){if(a.u){xHa(a);
var c=a.u,d=a.Y[0]?g.Oa:null;a.u=null;a.Y=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},xHa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.V&&(g.v.clearTimeout(a.V),a.V=null)},Q6=function(a){return a.u?a.u.readyState:0},S6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.oa+" "+a.P+" "+a.getStatus()+"]"},yHa=function(a){this.u=a;
this.B=new z6},zHa=function(a){var b=T6(a.u,a.On,"/mail/images/cleardot.gif");
a6(b);qHa(b.toString(),5E3,(0,g.z)(a.qH,a),3,2E3);a.Vg(1)},V6=function(a){var b=a.u.N;
if(null!=b)C6(5),b?(C6(11),U6(a.u,a,!1)):(C6(12),U6(a.u,a,!0));else if(a.Bf=new E6(a,void 0,void 0,void 0),a.Bf.Uk=a.Pv,b=a.u,b=T6(b,b.Mp()?a.uo:null,a.Qv),C6(5),!g.xe||g.$d(10))b6(b,"TYPE","xmlhttp"),F6(a.Bf,b,!1,a.uo,!1);else{b6(b,"TYPE","html");var c=a.Bf;a=!!a.uo;c.un=3;c.ij=a6(b.clone());nHa(c,a)}},W6=function(a,b,c){this.Ba=1;
this.u=[];this.C=[];this.D=new z6;this.K=a||null;this.N=null!=b?b:null;this.F=c||!1},AHa=function(a,b){this.u=a;
this.map=b;this.context=null},BHa=function(a,b,c,d){g.Kl.call(this,"timingevent",a);
this.size=b;this.Ep=d},CHa=function(a){g.Kl.call(this,"serverreachability",a)},FHa=function(a){DHa(a);
if(3==a.Ba){var b=a.cp++,c=a.ir.clone();$5(c,"SID",a.B);$5(c,"RID",b);$5(c,"TYPE","terminate");X6(a,c);b=new E6(a,a.B,b,void 0);b.un=2;b.ij=a6(c.clone());BGa(new Image,b.ij.toString());b.mn=g.A();G6(b)}EHa(a)},GHa=function(a){a.NH(1,0);
a.ir=T6(a,null,a.Ov);Y6(a)},DHa=function(a){a.lj&&(a.lj.abort(),a.lj=null);
a.nd&&(a.nd.cancel(),a.nd=null);a.ji&&(g.v.clearTimeout(a.ji),a.ji=null);Z6(a);a.nf&&(a.nf.cancel(),a.nf=null);a.pj&&(g.v.clearTimeout(a.pj),a.pj=null)},HHa=function(a,b){if(0==a.Ba)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new AHa(a.IL++,b));2!=a.Ba&&3!=a.Ba||Y6(a)},Y6=function(a){a.nf||a.pj||(a.pj=A6((0,g.z)(a.gE,a),0),a.tm=0)},JHa=function(a,b){if(1==a.Ba){if(!b){a.cp=Math.floor(1E5*Math.random());
var c=a.cp++,d=new E6(a,"",c,void 0);d.Uk=a.Am;var e=$6(a),f=a.ir.clone();$5(f,"RID",c);$5(f,"CVER","1");X6(a,f);hHa(d,f,e);a.nf=d;a.Ba=2}}else 3==a.Ba&&(b?IHa(a,b):0==a.u.length||a.nf||IHa(a))},IHa=function(a,b){if(b)if(6<a.Bk){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.cp-1;var d=$6(a)}else c=b.N,d=b.Gl;else c=a.cp++,d=$6(a);var e=a.ir.clone();$5(e,"SID",a.B);$5(e,"RID",c);$5(e,"AID",a.Mm);X6(a,e);c=new E6(a,a.B,c,a.tm+1);c.Uk=a.Am;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.nf=c;hHa(c,e,d)},X6=function(a,b){if(a.Be){var c=a.Be.NA();
c&&g.Hb(c,function(d,e){$5(b,e,d)})}},$6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Bk&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Zl:e.Zl},f++){e.Zl=a.u[f].u;var h=a.u[f].map;e.Zl=6>=a.Bk?f:e.Zl-d;try{g.Hb(h,function(l){return function(m,n){c.push("req"+l.Zl+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Zl+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},KHa=function(a){a.nd||a.ji||(a.I=1,a.ji=A6((0,g.z)(a.fE,a),0),a.em=0)},a7=function(a){if(a.nd||a.ji||3<=a.em)return!1;
a.I++;a.ji=A6((0,g.z)(a.fE,a),LHa(a,a.em));a.em++;return!0},U6=function(a,b,c){a.Xt=c;
a.Dh=b.Ci;a.F||GHa(a)},Z6=function(a){null!=a.Gk&&(g.v.clearTimeout(a.Gk),a.Gk=null)},LHa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},b7=function(a,b){if(2==b||9==b){var c=null;
a.Be&&(c=null);var d=(0,g.z)(a.wQ,a);c||(c=new g.Ym("//www.google.com/images/cleardot.gif"),a6(c));pHa(c.toString(),1E4,d)}else C6(2);MHa(a,b)},MHa=function(a,b){a.Ba=0;
a.Be&&a.Be.Yz(b);EHa(a);DHa(a)},EHa=function(a){a.Ba=0;
a.Dh=-1;if(a.Be)if(0==a.C.length&&0==a.u.length)a.Be.Ou();else{g.tb(a.C);var b=g.tb(a.u);a.C.length=0;a.u.length=0;a.Be.Ou(b)}},T6=function(a,b,c){var d=g.fn(c);
if(""!=d.u)b&&g.$m(d,b+"."+d.u),g.an(d,d.D);else{var e=window.location;d=FGa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.fo&&g.Hb(a.fo,function(f,h){$5(d,h,f)});
$5(d,"VER",a.Bk);X6(a,d);return d},NHa=function(){},OHa=function(){this.u=[];
this.B=[]},PHa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.u=new g.H(this.VO,0,this);g.C(this,this.u);this.Ee=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.V=a;this.I=b;this.C=new g.Qn;this.B=new c7(this.aQ,this);this.u=null;this.Cd=!1;this.F=null;this.P="";this.N=this.D=0;this.K=[];this.Y=c;this.X=d},QHa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.Xt,sessionId:a.u.B,arrayId:a.u.Mm}},RHa=function(a,b){a.N=b||0;
a.B.stop();e7(a);a.u&&(3==a.u.Ba&&JHa(a.u),FHa(a.u));a.N=0},f7=function(a){return!!a.u&&3==a.u.Ba},e7=function(a){if(a.u){var b=a.X(),c=a.u.Am||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Am=c}},SHa=function(a,b){(a.I.loungeIdToken=b)||a.B.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.wd(4,a))||"";b&&(this.port=":"+b);this.domain=g.xd(a)||"";a=g.Uc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.B=!1))},h7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Kd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Va(a.D,d,!0),onError:g.Va(a.C,e),vf:g.Va(a.F,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.nq(b,a)},WHa=function(){var a=THa;
UHa();j7.push(a);VHa(j7)},k7=function(a,b){UHa();
var c=j7,d=XHa(a,String(b));g.nb(c)?YHa(d):(VHa(c),g.Fb(c,function(e){e(d)}))},UHa=function(){j7||(j7=g.Na("yt.mdx.remote.debug.handlers_")||[],g.Ja("yt.mdx.remote.debug.handlers_",j7,void 0))},YHa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},VHa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];g.Fb(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},XHa=function(a,b){var c=(g.A()-ZHa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.P.call(this);
this.I=a;this.screens=[]},$Ha=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},aIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Je(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=$Ha(a,b[d])||c;return c},bIa=function(a,b){var c=a.screens.length;
a.screens=g.Je(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.P.call(this);
this.I=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Sa=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},cIa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=h7(a.B,"/pairing/get_lounge_token_batch");
i7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.AI,a),(0,g.z)(a.zI,a))}},q7=function(a){if(g.to("deprecate_pair_servlet_enabled"))return aIa(a,[]);
var b=LGa(RGa());b=g.Je(b,function(c){return!c.uuid});
return aIa(a,b)},s7=function(a,b){TGa(g.Oc(a.screens,JGa));
b&&SGa()},u7=function(a,b){g.P.call(this);
this.I=b;var c=g.nt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.lb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;t7("Initialized with "+g.Ej(this.u))},dIa=function(a,b,c){var d=h7(a.F,"/pairing/get_screen_availability");
i7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.u))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Ej(a.u)),a.u=b,a.W("screenChange"));eIa(a)},w7=function(a){isNaN(a.C)||g.Go(a.C);
a.C=g.Eo((0,g.z)(a.Fx,a),0<a.D&&a.D<g.A()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},fIa=function(a){var b={};
g.Fb(a.I(),function(c){c.token?b[c.token]=c.id:this.Sc("Requesting availability of screen w/o lounge token.")});
return b},eIa=function(a){a=g.Pb(g.Ib(a.u,function(b){return b}));
g.Bb(a);a.length?g.mt("yt-remote-online-screen-ids",a.join(","),60):g.ot("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};gIa(this)},iIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.If();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);dIa(a.u,l,function(m){e(m?l:null)})}else c?hIa(a,c,(0,g.z)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));dIa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},jIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},hIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.nq(h7(a.F,"/pairing/get_lounge_token_batch"),e)},kIa=function(a){a.screens=a.B.If();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},gIa=function(a){z7(a);
a.B=new r7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.II,a));kIa(a);a.C=LGa(g.nt("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.C));a.u=new u7(a.F,(0,g.z)(a.If,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.W("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.mt("yt-remote-automatic-screen-cache",g.Oc(a.C,JGa)));z7(a);a.D[b.uuid]=b.id;g.mt("yt-remote-device-id-map",a.D,31536E3);return b},z7=function(a){a.D=g.nt("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.P.call(this);
this.Y=c;this.N=a;this.u=b;this.K=null},B7=function(a,b){k7(a.Y,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.fR,this);this.D=(0,g.z)(this.vP,this);this.C=g.Eo((0,g.z)(function(){lIa(this,null)},this),12E4)},mIa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ej(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Oa,(0,g.z)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Ej(b))},lIa=function(a,b){g.Go(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.Ys,a),d=(0,g.z)(a.Qf,a);a.fB(b,c,d,5)}}else a.Qf(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.C=this.I=null;this.P="";this.ba=c;this.V=null;this.F=g.Oa;this.D=NaN;this.X=(0,g.z)(this.iR,this);this.B=g.Oa},nIa=function(a){a.B=a.N.nG(a.P,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Oa;
this.Ys(b)},a),(0,g.z)(function(b){this.B=g.Oa;
this.Qf(b)},a))},oIa=function(a){var b={};
b.pairingCode=a.P;b.theme=a.ba;VGa()&&(b.env_useStageMdx=1);return g.Gd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.B=g.Eo((0,g.z)(this.Nm,this,null),150)},F7=function(a,b,c,d){g.P.call(this);
this.B=a;this.K=b||"233637DE";this.I=c||"cl";this.N=d||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.mO,this)},pIa=function(a,b){return b?g.ib(a.C,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},THa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.F||!!a.C.length||!!a.u},I7=function(a,b,c){b!=a.u&&(g.cg(a.u),(a.u=b)?(c?a.W("yt-remote-cast2-receiver-resumed",b.u):a.W("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.dE,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.Nm(null)):a.W("yt-remote-cast2-session-change",null))},qIa=function(a){var b=a.B.mG(),c=a.u&&a.u.u;
a=g.Oc(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=pIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},wIa=function(a,b,c,d,e,f,h){rIa()?sIa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?tIa(a,c):(window.__onGCastApiAvailable=function(l,m){l?tIa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.ot("yt-remote-cast-available"),g.ot("yt-remote-cast-receiver"),uIa(),c(!1))},d?g.Ro("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?bHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(aHa(),t6(vIa.map(ZGa))))):J7("Cannot initialize because not running Chrome")},uIa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ja("yt.mdx.remote.cloudview.instance_",null,void 0);xIa(!1);g.No(O7);O7.length=0},P7=function(){return!!g.nt("yt-remote-cast-installed")},yIa=function(){var a=g.nt("yt-remote-cast-receiver");
return a?a.friendlyName:null},zIa=function(){J7("clearCurrentReceiver");
g.ot("yt-remote-cast-receiver")},AIa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.Mo("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},rIa=function(){var a=0<=g.Uc.search(/ (CrMo|Chrome|CriOS)\//);
return g.wB||a},BIa=function(a,b){N7().init(a,b)},sIa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.mt("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.mt("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.mt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.ot("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ja("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Na("yt.mdx.remote.cloudview.instance_")},tIa=function(a,b){M7(!0);
K7(!1);BIa(a,function(c){c?(xIa(!0),g.Oo("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.ot("yt-remote-cast-available"),g.ot("yt-remote-cast-receiver"),uIa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.mt("yt-remote-cast-installed",a)},Q7=function(){return!!g.Na("yt.mdx.remote.cloudview.apiReady_")},xIa=function(a){J7("setApiReady_ "+a);
g.Ja("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ja("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.u=null;this.hasNext=this.Eh=!1;this.P=this.N=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.Eh=!1;a.hasNext=!1;a.K=0;a.I=g.A();a.F=0;a.B=0;a.N=0;a.P=0;a.D=NaN;a.C=!1},V7=function(a){return a.Bb()?(g.A()-a.I)/1E3:0},W7=function(a,b){a.K=b;
a.I=g.A()},X7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Zb(a.u);b.hasPrevious=a.Eh;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.N;b.loadedTime=a.P;b.liveIngestionTime=a.D;return b},a8=function(a,b){g.P.call(this);
this.Ba=0;this.C=a;this.F=[];this.D=new OHa;this.B=this.u=null;this.N=(0,g.z)(this.wM,this);this.I=(0,g.z)(this.hp,this);this.K=(0,g.z)(this.vM,this);this.P=(0,g.z)(this.EM,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Iy,this),CIa(this))):c=3;0!=c&&(b?this.Iy(c):g.Eo((0,g.z)(function(){this.Iy(c)},this),0));
var d=AIa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},b8=function(a){return new T7(a.C.getPlayerContextData())},CIa=function(a){g.Fb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Va(this.iO,b),this))},a)},DIa=function(a){g.Fb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){DIa(a);
a.C.setPlayerContextData(Z7(b));CIa(a)},$7=function(a,b){a.B&&(a.B.removeUpdateListener(a.N),a.B.removeMediaListener(a.I),a.hp(null));
a.B=b;a.B&&(k7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.N),a.B.addMediaListener(a.I),a.B.media.length&&a.hp(a.B.media[0]))},EIa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.Sc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Sc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.P.call(this);
this.F=NaN;this.X=!1;this.N=this.K=this.P=this.V=NaN;this.Y=[];this.D=this.I=this.C=this.zb=this.u=null;this.fa=a;this.Y.push(g.bp(window,"beforeunload",(0,g.z)(this.tI,this)));this.B=[];this.zb=new T7;this.ba=b.id;this.u=FIa(this,c);this.u.subscribe("handlerOpened",this.AM,this);this.u.subscribe("handlerClosed",this.xM,this);this.u.subscribe("handlerError",this.yM,this);this.u.subscribe("handlerMessage",this.zM,this);SHa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.zb.videoId;
g.pt()&&g.mt("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},FIa=function(a,b){return new d7(h7(a.fa,"/bc"),b,!1,function(){return a.jG()})},j8=function(a,b){a.W("proxyStateChange",b)},GIa=function(a){a.F=g.Eo((0,g.z)(function(){i8("Connecting timeout");
this.om(1)},a),2E4)},k8=function(a){g.Go(a.F);
a.F=NaN},l8=function(a){g.Go(a.V);
a.V=NaN},HIa=function(a){m8(a);
a.P=g.Eo((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Go(a.P);
a.P=NaN},JIa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.u)&&isNaN(a.F))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.dB()&&a.zb.reset(),j8(a,1),n8(a,"getNowPlaying"),IIa(a)):a.om(1)},KIa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.zb.videoId&&(g.Vb(b.params)?a.zb.u=null:a.zb.u=b.params,a.W("remotePlayerChange"))},LIa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.zb.listId=b.params.listId||a.zb.listId;Y7(a.zb,c,d);a.W("remoteQueueChange")},NIa=function(a,b){b.params=b.params||{};
LIa(a,b);MIa(a,b);a.W("autoplayDismissed")},MIa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.zb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.zb.playerState&&(c=-1E3);a.zb.playerState=c;c=Number(b.params.loadedTime);a.zb.P=isNaN(c)?0:c;c=Number(b.params.duration);a.zb.N=isNaN(c)?0:c;c=a.zb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.zb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.zb.playerState?HIa(a):m8(a);a.W("remotePlayerChange")},OIa=function(a,b){if(-1E3!=
a.zb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.zb.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.zb,isNaN(c)?0:c);a.W("remotePlayerChange")}},PIa=function(a,b){var c="true"==b.params.muted;
a.zb.volume=parseInt(b.params.volume,10);a.zb.muted=c;a.W("remotePlayerChange")},QIa=function(a,b){a.I=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},RIa=function(a,b){var c="true"==b.params.hasNext;
a.zb.Eh="true"==b.params.hasPrevious;a.zb.hasNext=c;a.W("previousNextChange")},IIa=function(a){g.Go(a.N);
a.N=g.Eo((0,g.z)(a.om,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Ej(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.De=a;this.u=[];this.u.push(this.De.$_s("screenChange",(0,g.z)(this.dR,this)));this.u.push(this.De.$_s("onlineScreenChange",(0,g.z)(this.ON,this)))},WIa=function(a,b){b=g.L("MDX_CONFIG")||b;
NGa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),VGa()&&(p8.u="/api/loungedev"));q8||(q8=g.Na("yt.mdx.remote.deferredProxies_")||[],g.Ja("yt.mdx.remote.deferredProxies_",q8,void 0));SIa();var c=r8();if(!c){var d=new x7(p8);g.Ja("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);wIa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.Na("yt.mdx.remote.initialized_")&&(g.Ja("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Ej(b)),u8.push(g.Mo("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.Mo("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.Mo("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.Mo("yt-remote-cast2-session-change",TIa)),u8.push(g.Mo("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),zIa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.to("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.Ej(e)),UIa(e),c.start(),s8()||VIa())},YIa=function(){var a=XIa();
P7()&&g.nt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},XIa=function(){var a=r8().De.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return MGa(a)},A8=function(){var a=ZIa();
!a&&P7()&&yIa()&&(a={key:"cast-selector-receiver",name:yIa()});return a},ZIa=function(){var a=XIa(),b=y8();
b||(b=w8());return g.ib(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().If();return m6(b,a)},TIa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Na("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Na("yt.mdx.remote.currentScreenId_")},$Ia=function(a){g.Ja("yt.mdx.remote.currentScreenId_",a,void 0)},aJa=function(){return g.Na("yt.mdx.remote.connectData_")},v8=function(a){g.Ja("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Na("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||$Ia("");g.Ja("yt.mdx.remote.connection_",a,void 0);q8&&(g.Fb(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.pt();
if(!a)return null;var b=r8();if(!b)return null;b=b.If();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{$Ia(a.id);var c=new h8(p8,a,x8());c.connect(b,aJa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},VIa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),zIa(),t8("Skipping connecting because no session screen found."))},SIa=function(){var a=x8();
if(g.Vb(a)){a=p6();var b=g.nt("yt-remote-session-name")||"",c=g.nt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ja("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Na("yt.mdx.remote.channelParams_")||{}},UIa=function(a){a?(g.mt("yt-remote-session-app",a.app),g.mt("yt-remote-session-name",a.name)):(g.ot("yt-remote-session-app"),g.ot("yt-remote-session-name"));
g.Ja("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.module=a;this.J=b;this.qb=c;this.events=new g.ms(this);this.P=this.events.R(this.J,"onVolumeChange",this.FD);this.D=!1;this.suggestion=null;this.F=new g.gL(64);this.u=new g.H(this.sF,500,this);this.B=new g.H(this.tF,1E3,this);this.K=new v6(this.IQ,0,this);this.C={};this.N=new g.H(this.VF,1E3,this);this.I=new w6(this.seekTo,1E3,this);this.V=g.Oa;g.C(this,this.events);this.events.R(b,"onCaptionsTrackListChanged",this.rN);this.events.R(b,"captionschanged",this.tM);this.events.R(b,"captionssettingschanged",
this.wF);this.events.R(b,"videoplayerreset",this.Zs);this.events.R(b,"mdxautoplaycancel",function(){d.qb.tA()});
a=this.qb;a.la();a.subscribe("proxyStateChange",this.YD,this);a.subscribe("remotePlayerChange",this.np,this);a.subscribe("remoteQueueChange",this.Zs,this);a.subscribe("previousNextChange",this.UD,this);a.subscribe("nowAutoplaying",this.PD,this);a.subscribe("autoplayDismissed",this.qD,this);g.C(this,this.u);g.C(this,this.B);g.C(this,this.K);g.C(this,this.N);g.C(this,this.I);this.wF();this.Zs();this.np()},bJa=function(a){a.Dc(0);
a.u.stop();a.Ad(new g.gL(64))},K8=function(a,b){if(J8(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.ac(c,b));a.qb.kG(a.J.getVideoData(1).videoId,c);a.C=b8(a.qb).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.qb.playVideo(c.videoId,b,d,e,c.playerParams,c.gg,zGa(c));a.Ad(new g.gL(1))},cJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{BB:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return b8(a.qb).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"Connecting to your TV on web using a code will be going away soon"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"Learn more"},{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Z:"OK"}]}]}]});this.u=new g.RN(this,250);this.learnMoreButton=
this.ga("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ga("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.u);this.R(this.learnMoreButton,"click",this.B);this.R(this.okButton,"click",this.C)},N8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-popup-title",Z:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",Z:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],Z:"Cancel"},{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-confirm"],
Z:"Confirm"}]}]}]});this.u=new g.RN(this,250);this.cancelButton=this.ga("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ga("ytp-mdx-privacy-popup-confirm");g.C(this,this.u);this.R(this.cancelButton,"click",this.B);this.R(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",S:[{G:"div",L:"ytp-remote-display-status",S:[{G:"div",L:"ytp-remote-display-status-icon",S:[g.kN()]},{G:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.RN(this,250);g.C(this,this.u);this.R(a,"presentingplayerstatechange",this.B);dJa(this,g.DI(a))},dJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.uJ("Error on $RECEIVER_NAME",c):b.Bb()||g.T(b,4)?g.uJ("Playing on $RECEIVER_NAME",c):g.uJ("Connected to $RECEIVER_NAME",c);a.ua("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.IZ.call(this,"Play on",0,a,b);
this.J=a;this.dk={};this.R(a,"onMdxReceiversChange",this.D);this.R(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.uS.call(this,a);
this.Pg={key:k6(),name:"This computer"};this.qh=null;this.subscriptions=[];this.ox=this.qb=null;this.dk=[this.Pg];this.nj=this.Pg;this.xc=new g.gL(64);this.UB=0;this.Td=-1;this.Pm=null;this.rp=this.ks=!1;this.Fl=this.hn=null;if(!g.tC(this.player.T())){a=this.player;var b=g.GW(a);b&&(b=b.Rk())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.vP(a,b.element,4);this.hn=new N8;g.C(this,this.hn);g.vP(a,this.hn.element,4);g.R(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Pm=new M8,g.C(this,this.Pm),g.vP(a,this.Pm.element,4));this.rp=!!w8();this.ks=!!g.nt("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.Fl&&(a.player.removeEventListener("presentingplayerstatechange",a.Fl),a.Fl=null)},eJa=function(a,b,c){a.xc=c;
a.player.W("presentingplayerstatechange",new g.LI(c,b))},fJa=function(a,b,c){var d=!1;
1===b?d=!a.rp:2===b&&(d=!a.ks);d&&g.NI(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.nj.key)if(b.key===a.Pg.key)B8();
else{if(a.Pm&&!a.ks&&b!==a.Pg&&"cast-selector-receiver"!==b.key&&g.DC(a.player.T()))gJa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.rp||!a.hn);(c?0:g.DC(a.player.T())||g.HC(a.player.T()))&&hJa(a)}a.nj=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ia(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.gg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=zGa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Ej(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().If(),(c=m6(c,b.key))&&C8(c,1))}},hJa=function(a){g.DI(a.player).Bb()?a.player.pauseVideo():(a.Fl=function(b){fJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Fl));
a.hn&&a.hn.lc();z8()||(G8=!0)},gJa=function(a){g.DI(a.player).Bb()?a.player.pauseVideo():(a.Fl=function(b){fJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Fl));
a.Pm&&a.Pm.lc();z8()||(G8=!0)},mHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},L6={"'":"\\'"},iJa={},IGa={JR:"atp",HU:"ska",sU:"que",FT:"mus",GU:"sus",GS:"dsp",zU:"seq"},s6,o6="",$Ga=WGa("loadCastFramework")||WGa("loadCastApplicationFramework"),vIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Xa(v6,g.B);g.k=v6.prototype;g.k.qI=function(a){this.D=arguments;this.u=!1;this.Sa?this.C=g.A()+this.Ee:this.Sa=g.Tm(this.F,this.Ee)};
g.k.stop=function(){this.Sa&&(g.v.clearTimeout(this.Sa),this.Sa=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.aa=function(){this.stop();v6.Wc.aa.call(this)};
g.k.rI=function(){this.C?(this.Sa=g.Tm(this.F,this.C-g.A()),this.C=null):(this.Sa=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(w6,g.B);g.k=w6.prototype;g.k.kC=function(a){this.C=arguments;this.Sa||this.B?this.u=!0:x6(this)};
g.k.stop=function(){this.Sa&&(g.v.clearTimeout(this.Sa),this.Sa=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Sa||(this.u=!1,x6(this))};
g.k.aa=function(){g.B.prototype.aa.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var B6=new g.hm;g.u(cHa,g.Kl);D6.prototype.u=null;D6.prototype.getOptions=function(){var a;(a=this.u)||(a={},eHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Xa(dHa,D6);T8=new dHa;g.k=E6.prototype;g.k.Uk=null;g.k.eh=!1;g.k.Bn=null;g.k.Fy=null;g.k.mn=null;g.k.un=null;g.k.ij=null;g.k.ek=null;g.k.Gl=null;g.k.Nd=null;g.k.eq=0;g.k.jh=null;g.k.au=null;g.k.xj=null;g.k.vo=-1;g.k.iF=!0;g.k.Ak=!1;g.k.Rv=0;g.k.nt=null;var jHa={},H6={};g.k=E6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.OP=function(a){a=a.target;var b=this.nt;b&&3==Q6(a)?b.kC():this.gG(a)};
g.k.gG=function(a){try{if(a==this.Nd)a:{var b=Q6(this.Nd),c=this.Nd.I,d=this.Nd.getStatus();if(g.xe&&!g.$d(10)||g.ze&&!g.Zd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pg&&!S6(this.Nd))break a;this.Ak||4!=b||7==c||(8==c||0>=d?this.u.Vg(3):this.u.Vg(2));M6(this);var e=this.Nd.getStatus();this.vo=e;var f=S6(this.Nd);(this.eh=200==e)?(4==b&&J6(this),this.I?(kHa(this,b,f),g.pg&&this.eh&&3==b&&(this.D.ra(this.C,"tick",this.IP),this.C.start())):I6(this,f),this.eh&&!this.Ak&&(4==b?this.u.Dr(this):(this.eh=
!1,G6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.xj=3,C6(13)):(this.xj=0,C6(14)),J6(this),K6(this))}}catch(h){this.Nd&&S6(this.Nd)}finally{}};
g.k.IP=function(){var a=Q6(this.Nd),b=S6(this.Nd);this.eq<b.length&&(M6(this),kHa(this,a,b),this.eh&&4!=a&&G6(this))};
g.k.cP=function(a){A6((0,g.z)(this.bP,this,a),0)};
g.k.bP=function(a){this.Ak||(M6(this),I6(this,a),G6(this))};
g.k.hE=function(a){A6((0,g.z)(this.aP,this,a),0)};
g.k.aP=function(a){this.Ak||(J6(this),this.eh=a,this.u.Dr(this),this.u.Vg(4))};
g.k.cancel=function(){this.Ak=!0;J6(this)};
g.k.oP=function(){this.Bn=null;var a=g.A();0<=a-this.Fy?(2!=this.un&&this.u.Vg(3),J6(this),this.xj=2,C6(18),K6(this)):oHa(this,this.Fy-a)};
g.k.getLastError=function(){return this.xj};g.Xa(O6,g.hm);var vHa=/^https?$/i,jJa=["POST","PUT"];g.k=O6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.P+"; newUri="+a);b=b?b.toUpperCase():"GET";this.P=a;this.D="";this.I=0;this.oa=b;this.fa=!1;this.B=!0;this.u=this.ba?fHa(this.ba):fHa(T8);this.Y=this.ba?this.ba.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.VD,this);try{d6(R6(this,"Opening Xhr")),this.ha=!0,this.u.open(b,String(a),!0),this.ha=!1}catch(f){d6(R6(this,"Error opening Xhr: "+f.message));uHa(this,f);return}a=
c||"";var e=this.headers.clone();d&&EGa(d,function(f,h){e.set(h,f)});
d=g.ib(e.eg(),sHa);c=g.v.FormData&&a instanceof g.v.FormData;!g.lb(jJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.za&&(this.u.responseType=this.za);"withCredentials"in this.u&&this.u.withCredentials!==this.ea&&(this.u.withCredentials=this.ea);try{xHa(this),0<this.K&&(this.X=rHa(this.u),d6(R6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.oB,this)):this.V=g.Tm(this.oB,this.K,this)),d6(R6(this,"Sending request")),this.N=!0,this.u.send(a),this.N=!1}catch(f){d6(R6(this,"Send error: "+f.message)),uHa(this,f)}};
g.k.oB=function(){"undefined"!=typeof g.$0&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,R6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.B&&(R6(this,"Aborting"),this.B=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.k.aa=function(){this.u&&(this.B&&(this.B=!1,this.F=!0,this.u.abort(),this.F=!1),P6(this,!0));O6.Wc.aa.call(this)};
g.k.VD=function(){this.la()||(this.ha||this.N||this.F?wHa(this):this.lO())};
g.k.lO=function(){wHa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<Q6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=yHa.prototype;g.k.Pv=null;g.k.Bf=null;g.k.ot=!1;g.k.nB=null;g.k.fr=null;g.k.ww=null;g.k.Qv=null;g.k.Ba=null;g.k.Ci=-1;g.k.uo=null;g.k.On=null;g.k.connect=function(a){this.Qv=a;a=T6(this.u,null,this.Qv);C6(3);this.nB=g.A();var b=this.u.K;null!=b?(this.uo=b[0],(this.On=b[1])?(this.Ba=1,zHa(this)):(this.Ba=2,V6(this))):(b6(a,"MODE","init"),this.Bf=new E6(this,void 0,void 0,void 0),this.Bf.Uk=this.Pv,F6(this.Bf,a,!1,null,!0),this.Ba=0)};
g.k.qH=function(a){if(a)this.Ba=2,V6(this);else{C6(4);var b=this.u;b.Dh=b.lj.Ci;b7(b,9)}a&&this.Vg(2)};
g.k.av=function(a){return this.u.av(a)};
g.k.abort=function(){this.Bf&&(this.Bf.cancel(),this.Bf=null);this.Ci=-1};
g.k.mB=function(){return!1};
g.k.ZD=function(a,b){this.Ci=a.vo;if(0==this.Ba)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.Dh=this.Ci;b7(c,2);return}this.uo=c[0];this.On=c[1]}else c=this.u,c.Dh=this.Ci,b7(c,2);else if(2==this.Ba)if(this.ot)C6(7),this.ww=g.A();else if("11111"==b){if(C6(6),this.ot=!0,this.fr=g.A(),c=this.fr-this.nB,!g.xe||g.$d(10)||500>c)this.Ci=200,this.Bf.cancel(),C6(12),U6(this.u,this,!0)}else C6(8),this.fr=this.ww=g.A(),this.ot=!1};
g.k.Dr=function(){this.Ci=this.Bf.vo;if(this.Bf.eh)0==this.Ba?this.On?(this.Ba=1,zHa(this)):(this.Ba=2,V6(this)):2==this.Ba&&((!g.xe||g.$d(10)?!this.ot:200>this.ww-this.fr)?(C6(11),U6(this.u,this,!1)):(C6(12),U6(this.u,this,!0)));else{0==this.Ba?C6(9):2==this.Ba&&C6(10);var a=this.u;this.Bf.getLastError();a.Dh=this.Ci;b7(a,2)}};
g.k.Mp=function(){return this.u.Mp()};
g.k.isActive=function(){return this.u.isActive()};
g.k.Vg=function(a){this.u.Vg(a)};g.k=W6.prototype;g.k.Am=null;g.k.fo=null;g.k.nf=null;g.k.nd=null;g.k.Ov=null;g.k.ir=null;g.k.Oz=null;g.k.Cr=null;g.k.cp=0;g.k.IL=0;g.k.Be=null;g.k.pj=null;g.k.ji=null;g.k.Gk=null;g.k.lj=null;g.k.Xt=null;g.k.Mm=-1;g.k.TB=-1;g.k.Dh=-1;g.k.tm=0;g.k.em=0;g.k.Bk=8;g.Xa(BHa,g.Kl);g.Xa(CHa,g.Kl);g.k=W6.prototype;g.k.connect=function(a,b,c,d,e){C6(0);this.Ov=b;this.fo=c||{};d&&void 0!==e&&(this.fo.OSID=d,this.fo.OAID=e);this.F?(A6((0,g.z)(this.eA,this,a),100),GHa(this)):this.eA(a)};
g.k.eA=function(a){this.lj=new yHa(this);this.lj.Pv=this.Am;this.lj.B=this.D;this.lj.connect(a)};
g.k.mB=function(){return 0==this.Ba};
g.k.gE=function(a){this.pj=null;JHa(this,a)};
g.k.fE=function(){this.ji=null;this.nd=new E6(this,this.B,"rpc",this.I);this.nd.Uk=this.Am;this.nd.Rv=0;var a=this.Oz.clone();$5(a,"RID","rpc");$5(a,"SID",this.B);$5(a,"CI",this.Xt?"0":"1");$5(a,"AID",this.Mm);X6(this,a);if(!g.xe||g.$d(10))$5(a,"TYPE","xmlhttp"),F6(this.nd,a,!0,this.Cr,!1);else{$5(a,"TYPE","html");var b=this.nd,c=!!this.Cr;b.un=3;b.ij=a6(a.clone());nHa(b,c)}};
g.k.ZD=function(a,b){if(0!=this.Ba&&(this.nd==a||this.nf==a))if(this.Dh=a.vo,this.nf==a&&3==this.Ba)if(7<this.Bk){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.ji){if(this.nd)if(this.nd.mn+3E3<this.nf.mn)Z6(this),this.nd.cancel(),this.nd=null;else break a;a7(this);C6(19)}}else this.TB=c[1],0<this.TB-this.Mm&&37500>c[2]&&this.Xt&&0==this.em&&!this.Gk&&(this.Gk=A6((0,g.z)(this.nM,this),6E3));else b7(this,11)}else b!=iJa.gS.u&&b7(this,11);else if(this.nd==
a&&Z6(this),!g.rc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Mm=e[0];e=e[1];2==this.Ba?"c"==e[0]?(this.B=e[1],this.Cr=e[2],e=e[3],null!=e?this.Bk=e:this.Bk=6,this.Ba=3,this.Be&&this.Be.aA(),this.Oz=T6(this,this.Mp()?this.Cr:null,this.Ov),KHa(this)):"stop"==e[0]&&b7(this,7):3==this.Ba&&("stop"==e[0]?b7(this,7):"noop"!=e[0]&&this.Be&&this.Be.Zz(e),this.em=0)}}};
g.k.nM=function(){null!=this.Gk&&(this.Gk=null,this.nd.cancel(),this.nd=null,a7(this),C6(20))};
g.k.Dr=function(a){if(this.nd==a){Z6(this);this.nd=null;var b=2}else if(this.nf==a)this.nf=null,b=1;else return;this.Dh=a.vo;if(0!=this.Ba)if(a.eh)1==b?(b=B6,b.dispatchEvent(new BHa(b,a.Gl?a.Gl.length:0,g.A()-a.mn,this.tm)),Y6(this),this.C.length=0):KHa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Dh)){if(d=1==b)this.nf||this.pj||1==this.Ba||2<=this.tm?d=!1:(this.pj=A6((0,g.z)(this.gE,this,a),LHa(this,this.tm)),this.tm++,d=!0);d=!(d||2==b&&a7(this))}if(d)switch(c){case 1:b7(this,
5);break;case 4:b7(this,10);break;case 3:b7(this,6);break;case 7:b7(this,12);break;default:b7(this,2)}}};
g.k.NH=function(a){if(!g.lb(arguments,this.Ba))throw Error("Unexpected channel state: "+this.Ba);};
g.k.wQ=function(a){a?C6(2):(C6(1),MHa(this,8))};
g.k.av=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.ea=!1;return a};
g.k.isActive=function(){return!!this.Be&&this.Be.isActive(this)};
g.k.Vg=function(a){var b=B6;b.dispatchEvent(new CHa(b,a))};
g.k.Mp=function(){return!(!g.xe||g.$d(10))};
g.k=NHa.prototype;g.k.aA=function(){};
g.k.Zz=function(){};
g.k.Yz=function(){};
g.k.Ou=function(){};
g.k.NA=function(){return{}};
g.k.isActive=function(){return!0};g.k=OHa.prototype;g.k.isEmpty=function(){return g.nb(this.u)&&g.nb(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.lb(this.u,a)||g.lb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.vAa)(b,a);0<=c?(g.pb(b,c),b=!0):b=!1;return b||g.qb(this.B,a)};
g.k.Qe=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Xa(c7,g.B);g.k=c7.prototype;g.k.VO=function(){this.Ee=Math.min(3E5,2*this.Ee);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.Ee+15E3*Math.random();this.u.tb(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.Ee=5E3};g.Xa(d7,NHa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.Tj=function(a){return this.C.Vk(a)};
g.k.W=function(a,b){return this.C.W.apply(this.C,arguments)};
g.k.dispose=function(){this.Cd||(this.Cd=!0,g.cg(this.C),RHa(this),g.cg(this.B),this.B=null,this.X=function(){return""})};
g.k.la=function(){return this.Cd};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.Ba){this.P="";this.B.stop();this.F=a||null;this.D=b||0;a=this.V+"/test";b=this.V+"/bind";var d=new W6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Y),e=this.u;e&&(e.Be=null);d.Be=this;this.u=d;e7(this);e?this.u.connect(a,b,this.I,e.B,e.Mm):c?this.u.connect(a,b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.ac(c,b);this.B.isActive()||2==(this.u?this.u.Ba:0)?this.K.push(c):f7(this)&&(e7(this),HHa(this.u,c))};
g.k.aA=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)HHa(this.u,a[b])}this.W("handlerOpened")};
g.k.Yz=function(a){var b=2==a&&401==this.u.Dh;4==a||b||this.B.start();this.W("handlerError",a)};
g.k.Ou=function(a){if(!this.B.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.NA=function(){var a={v:2};this.P&&(a.gsessionid=this.P);0!=this.D&&(a.ui=""+this.D);0!=this.N&&(a.ui=""+this.N);this.F&&g.ac(a,this.F);return a};
g.k.Zz=function(a){"S"==a[0]?this.P=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),FHa(this.u)):this.W("handlerMessage",new PHa(a[0],a[1]))};
g.k.aQ=function(){this.B.isActive();var a=this.u,b=0;a.nd&&b++;a.nf&&b++;0==b&&this.connect(this.F,this.D)};g7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.F=function(a){a(Error("request timed out"))};var ZHa=g.A(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Xa(o7,g.P);o7.prototype.If=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.I,a)};g.u(p7,g.P);g.k=p7.prototype;g.k.start=function(){!this.u&&isNaN(this.Sa)&&this.lG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Sa)||(g.Go(this.Sa),this.Sa=NaN)};
g.k.aa=function(){this.stop();g.P.prototype.aa.call(this)};
g.k.lG=function(){this.Sa=NaN;this.u=g.nq(h7(this.I,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.bR,this),onError:(0,g.z)(this.aR,this),vf:(0,g.z)(this.cR,this)})};
g.k.bR=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.W("pairingComplete",new g6(c))};
g.k.aR=function(a){this.u=null;a.status&&404==a.status?this.B>=kJa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=kJa[this.B],this.Sa=g.Eo((0,g.z)(this.lG,this),a),this.B++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.cR=function(){this.u=null;this.W("pairingFailed",Error("Server not responding"))};
var kJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Xa(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.W("screenChange");!g.nt("yt-remote-lounge-token-expiration")&&cIa(this);g.Go(this.u);this.u=g.Eo((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);$Ha(this,a);s7(this,!1);this.W("screenChange");b(a);a.token||cIa(this)};
g.k.remove=function(a,b){var c=q7(this);bIa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Vt=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.aa=function(){g.Go(this.u);r7.Wc.aa.call(this)};
g.k.AI=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.I,"Missed "+b+" lounge tokens.")};
g.k.zI=function(a){k7(this.I,"Requesting lounge tokens failed: "+a)};g.u(u7,g.P);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.nt("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?w7(this):(this.D=g.A()+3E5,g.mt("yt-remote-fast-check-period",this.D),this.Fx())};
g.k.isEmpty=function(){return g.Vb(this.u)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.I(),b=g.Ib(this.u,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.aa=function(){g.Go(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.P.prototype.aa.call(this)};
g.k.Fx=function(){g.Go(this.C);this.C=NaN;this.B&&this.B.abort();var a=fIa(this);if(c6(a)){var b=h7(this.F,"/pairing/get_screen_availability");this.B=i7(this.F,b,{lounge_token:g.Pb(a).join(",")},(0,g.z)(this.GO,this,a),(0,g.z)(this.FO,this))}else v7(this,{}),w7(this)};
g.k.GO=function(a,b){this.B=null;var c=g.Pb(fIa(this));if(g.Cb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.Sc("Changing Screen set during request."),this.Fx()};
g.k.FO=function(a){this.Sc("Screen availability failed: "+a);this.B=null;w7(this)};
g.k.Sc=function(a){k7("OnlineScreenService",a)};g.Xa(x7,o7);g.k=x7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.W("screenChange"),this.u.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.Vt=function(a,b,c,d){this.B.contains(a)?this.B.Vt(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.I,a),d(Error(a)))};
g.k.If=function(a){return a?this.screens:g.sb(this.screens,g.Je(this.C,function(b){return!this.contains(b)},this))};
g.k.mG=function(){return g.Je(this.If(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.nG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.cg(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.cg(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.eR=function(a,b,c,d){g.nq(h7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new g6(f.screen||{});if(!h.name||jIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);jIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
vf:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.aa=function(){g.cg(this.B);g.cg(this.u);x7.Wc.aa.call(this)};
g.k.II=function(){kIa(this);this.W("screenChange");this.u.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Xa(A7,g.P);g.k=A7.prototype;g.k.getScreen=function(){return this.K};
g.k.Ys=function(a){this.K=a;this.W("sessionScreen",this.K)};
g.k.Qf=function(a){this.la()||(a&&B7(this,""+a),this.K=null,this.W("sessionScreen",null))};
g.k.info=function(a){k7(this.Y,a)};
g.k.pG=function(){return null};
g.k.Px=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.aa=function(){this.Px("");A7.Wc.aa.call(this)};g.u(C7,A7);g.k=C7.prototype;g.k.Ox=function(a){if(this.B){if(this.B==a)return;B7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);mIa(this)};
g.k.Nm=function(a){this.info("launchWithParams no-op for Cast: "+g.Ej(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.Qf()},this),(0,g.z)(function(){this.Qf(Error("Failed to stop receiver app."))},this)):this.Qf(Error("Stopping cast device witout session."))};
g.k.Px=function(){};
g.k.aa=function(){this.info("disposeInternal");g.Go(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;A7.prototype.aa.call(this)};
g.k.vP=function(a,b){if(!this.la())if(b){var c=y6(b);if(g.Sa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ej(c));switch(d){case "mdxSessionStatus":lIa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.fB=function(a,b,c,d){iIa(this.N,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Eo((0,g.z)(this.fB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.pG=function(){return this.B};
g.k.fR=function(a){this.la()||a||(B7(this,"Cast session died."),this.Qf())};g.u(D7,A7);g.k=D7.prototype;g.k.Ox=function(a){this.C=a;this.C.addUpdateListener(this.X)};
g.k.Nm=function(a){this.V=a;this.F()};
g.k.stop=function(){this.B();this.B=g.Oa;g.Go(this.D);this.C?this.C.stop((0,g.z)(this.Qf,this,null),(0,g.z)(this.Qf,this,"Failed to stop DIAL device.")):this.Qf()};
g.k.aa=function(){this.B();this.B=g.Oa;g.Go(this.D);this.C&&this.C.removeUpdateListener(this.X);this.C=null;A7.prototype.aa.call(this)};
g.k.iR=function(a){this.la()||a||(B7(this,"DIAL session died."),this.B(),this.B=g.Oa,this.Qf())};
g.k.bw=function(a){this.P=k6();if(this.V){var b=new chrome.cast.DialLaunchResponse(!0,oIa(this));a(b);nIa(this)}else this.F=(0,g.z)(function(){g.Go(this.D);this.F=g.Oa;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,oIa(this));a(c);nIa(this)},this),this.D=g.Eo((0,g.z)(function(){this.F()},this),100)};
g.k.ZI=function(a,b,c){iIa(this.N,this.I.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Ys(d),b(new chrome.cast.DialLaunchResponse(!1))):this.bw(b,c)},this),(0,g.z)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.bw(b,c)},this))};g.u(E7,A7);E7.prototype.stop=function(){this.Qf()};
E7.prototype.Ox=function(){};
E7.prototype.Nm=function(){g.Go(this.B);this.B=NaN;var a=m6(this.N.If(),this.u.label);a?this.Ys(a):this.Qf(Error("No such screen"))};
E7.prototype.aa=function(){g.Go(this.B);this.B=NaN;A7.prototype.aa.call(this)};g.u(F7,g.P);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.N||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.qO,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.bE,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.MM,this);chrome.cast.initialize(c,(0,g.z)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.D),WHa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.oG,this)),this.C=qIa(this),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(h){this.Sc("Failed to set initial custom receivers: "+g.Ej(h))},this)),this.W("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.z)(function(h){this.Sc("Failed to initialize API: "+g.Ej(h));
b(!1)},this))};
g.k.gQ=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.u.u.friendlyName),I7(this,null)}if(a&&b){if(!this.u){c=m6(this.B.If(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=pIa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.Oa,(0,g.z)(function(e){this.Sc("Failed to set initial custom receivers: "+g.Ej(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.B,d),!0)}this.u.Px(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.hQ=function(a){this.la()?this.Sc("Setting connection data on disposed cast v2"):this.u?this.u.Nm(a):this.Sc("Setting connection data without a session")};
g.k.hR=function(){this.la()?this.Sc("Stopping session on disposed cast v2"):this.u?(this.u.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.bE,this),(0,g.z)(this.IO,this))};
g.k.aa=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.oG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=THa,b=g.Na("yt.mdx.remote.debug.handlers_");g.qb(b||[],a);g.cg(this.u);g.P.prototype.aa.call(this)};
g.k.Sc=function(a){k7("Controller",a)};
g.k.dE=function(a,b){this.u==a&&(b||I7(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.mO=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.W("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.B,a,this.I));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.B,a));break;default:this.Sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Sc("Stopping receiver w/o session: "+a.friendlyName)}else this.Sc("onReceiverAction_ called without receiver.")};
g.k.MM=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return G7("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.B,b,this.I))}b=this.u;b.I=a;return b.I.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.ZI,b,(b.I.extraData||{}).screenId||null)):new Promise((0,g.z)(b.bw,b))};
g.k.bE=function(a){if(!this.la()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.B,b),!0);else{this.Sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=m6(this.B.If(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.cg(this.u),this.u=new C7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.dE,this,this.u)),this.u.Nm(null));this.u.Ox(a)}}};
g.k.gR=function(){return this.u?this.u.pG():null};
g.k.IO=function(a){this.la()||(this.Sc("Failed to estabilish a session: "+g.Ej(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.qO=function(a){G7("Receiver availability updated: "+a);if(!this.la()){var b=H7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.W("yt-remote-cast2-availability-change",H7(this))}};
g.k.oG=function(){this.la()||(this.C=qIa(this),G7("Updating custom receivers: "+g.Ej(this.C)),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(){this.Sc("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.hQ;F7.prototype.setConnectedScreenStatus=F7.prototype.gQ;F7.prototype.stopSession=F7.prototype.hR;F7.prototype.getCastSession=F7.prototype.gR;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.Eh=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.N=a.duration,this.P=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Bb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.N+V7(this):this.N};
g.k.clone=function(){return new T7(Z7(this))};g.u(a8,g.P);g.k=a8.prototype;g.k.play=function(){1==this.Ba?(this.u?this.u.play(null,g.Oa,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.W("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.Ba?(this.u?this.u.pause(null,g.Oa,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.W("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.Ba){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Bb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Oa,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.W("remotePlayerChange")}else c8(this,g.Va(this.seekTo,a))};
g.k.stop=function(){if(1==this.Ba){this.u?this.u.stop(null,g.Oa,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.W("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.Ba){var c=b8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Va(this.setVolume,a,b))};
g.k.kG=function(a,b){if(1==this.Ba){var c=b8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ej(b.style),g.ac(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Va(this.kG,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.Ba){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Va(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Ej(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.jt=function(a,b){if(1==this.Ba){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Va(this.jt,a,b))};
g.k.nextVideo=function(a,b){if(1==this.Ba){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Va(this.nextVideo,a,b))};
g.k.tA=function(){1==this.Ba?f8(this,"dismissAutoplay"):c8(this,this.tA)};
g.k.dispose=function(){if(3!=this.Ba){var a=this.Ba;this.Ba=3;this.W("proxyStateChange",a,this.Ba)}g.P.prototype.dispose.call(this)};
g.k.aa=function(){DIa(this);this.C=null;this.D.clear();$7(this,null);g.P.prototype.aa.call(this)};
g.k.Iy=function(a){if((a!=this.Ba||2==a)&&3!=this.Ba&&0!=a){var b=this.Ba;this.Ba=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.nb(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.iO=function(a,b){this.W(a,b)};
g.k.wM=function(a){if(!a)this.hp(null),$7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.hp=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),EIa(this),this.W("remotePlayerChange")};
g.k.vM=function(a){a?(EIa(this),this.W("remotePlayerChange")):this.hp(null)};
g.k.iy=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.EM=function(){var a=AIa();a&&$7(this,a)};
g.k.Sc=function(a){k7("CP",a)};g.u(h8,g.P);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.zb.listId=c);this.zb.videoId=d;this.zb.index=h||0;this.zb.state=3;W7(this.zb,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Ej(l));this.u.connect({method:"setPlaylist",
params:g.Ej(l)},a,QGa())}else i8("Connecting without params"),this.u.connect({},a,QGa());GIa(this)};
g.k.dispose=function(){this.la()||(this.W("beforeDispose"),j8(this,3));g.P.prototype.dispose.call(this)};
g.k.aa=function(){k8(this);m8(this);l8(this);g.Go(this.K);this.K=NaN;g.Go(this.N);this.N=NaN;this.C=null;g.cp(this.Y);this.Y.length=0;this.u.dispose();g.P.prototype.aa.call(this);this.D=this.I=this.B=this.zb=this.u=null};
g.k.tI=function(){this.om(2)};
g.k.AM=function(){i8("Channel opened");this.X&&(this.X=!1,l8(this),this.V=g.Eo((0,g.z)(function(){i8("Timing out waiting for a screen.");this.om(1)},this),15E3));
UGa(QHa(this.u),this.ba)};
g.k.xM=function(){i8("Channel closed");isNaN(this.F)?r6(!0):r6();this.dispose()};
g.k.yM=function(a){r6();isNaN(this.oo())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.X=!0,i8("Channel error: "+a+" with reconnection in "+this.oo()+" ms"),j8(this,2))};
g.k.zM=function(a){a.params?i8("Received: action="+a.action+", params="+g.Ej(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.B=g.Oc(a,function(c){return new f6(c)});
a=!!g.ib(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
JIa(this,a);break;case "loungeScreenDisconnected":g.rb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
JIa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.ib(this.B,function(c){return b?c.id==b.id:!1})||AGa(this.B,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.rb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":LIa(this,a);break;case "nowPlaying":NIa(this,a);break;case "onStateChange":MIa(this,a);break;case "onAdStateChange":OIa(this,a);break;case "onVolumeChanged":PIa(this,a);break;case "onSubtitlesTrackChanged":KIa(this,a);break;case "nowAutoplaying":QIa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.W("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.W("autoplayModeChange",this.D);"DISABLED"==this.D&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":RIa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.WP=function(){if(this.C){var a=this.C;this.C=null;this.zb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.kI=function(){var a=3;this.la()||(a=0,isNaN(this.oo())?f7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.om=function(a){i8("Disconnecting with "+a);k8(this);this.W("beforeDisconnect",a);1==a&&r6();RHa(this.u,a);this.dispose()};
g.k.iI=function(){var a=this.zb;this.C&&(a=this.zb.clone(),Y7(a,this.C,a.index));return Z7(a)};
g.k.iQ=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.zb.videoId&&(this.C=b.videoId,g.Go(this.K),this.K=g.Eo((0,g.z)(this.WP,this),5E3));var c=[];this.zb.listId==b.listId&&this.zb.videoId==b.videoId&&this.zb.index==b.index||c.push("remoteQueueChange");this.zb.playerState==b.playerState&&this.zb.volume==b.volume&&this.zb.muted==b.muted&&X7(this.zb)==X7(b)&&g.Ej(this.zb.u)==g.Ej(b.u)||c.push("remotePlayerChange");this.zb.reset(a);g.Fb(c,function(d){this.W(d)},this)};
g.k.dB=function(){var a=this.u.I.id,b=g.ib(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.oo=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.XH=function(){return this.D||"UNSUPPORTED"};
g.k.YH=function(){return this.I||""};
g.k.ZQ=function(){if(!isNaN(this.oo())){var a=this.u.B;g.sn(a.u);a.start()}};
g.k.eQ=function(a,b){n8(this,a,b);IIa(this)};
g.k.jG=function(){var a=g.wq("SID","")||"",b=g.wq("SAPISID","")||"",c=g.wq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.of(g.Te(a),2);b=g.of(g.Te(b),2);c=g.of(g.Te(c),2);return g.of(g.Te(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Tj;h8.prototype.getProxyState=h8.prototype.kI;h8.prototype.disconnect=h8.prototype.om;h8.prototype.getPlayerContextData=h8.prototype.iI;h8.prototype.setPlayerContextData=h8.prototype.iQ;h8.prototype.getOtherConnectedRemoteId=h8.prototype.dB;h8.prototype.getReconnectTimeout=h8.prototype.oo;h8.prototype.getAutoplayMode=h8.prototype.XH;h8.prototype.getAutoplayVideoId=h8.prototype.YH;h8.prototype.reconnect=h8.prototype.ZQ;
h8.prototype.sendMessage=h8.prototype.eQ;h8.prototype.getXsrfToken=h8.prototype.jG;g.u(o8,o7);g.k=o8.prototype;g.k.If=function(a){return this.De.$_gs(a)};
g.k.contains=function(a){return!!this.De.$_c(a)};
g.k.get=function(a){return this.De.$_g(a)};
g.k.start=function(){this.De.$_st()};
g.k.add=function(a,b,c){this.De.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.De.$_r(a,b,c)};
g.k.Vt=function(a,b,c,d){this.De.$_un(a,b,c,d)};
g.k.aa=function(){for(var a=0,b=this.u.length;a<b;++a)this.De.$_ubk(this.u[a]);this.u.length=0;this.De=null;o7.prototype.aa.call(this)};
g.k.dR=function(){this.W("screenChange")};
g.k.ON=function(){this.W("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.eR;x7.prototype.$_gsppc=x7.prototype.nG;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.Vt;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.If;x7.prototype.$_gos=x7.prototype.mG;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Tj;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.B);g.k=I8.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.u.stop();this.B.stop();this.K.stop();this.V();var a=this.qb;a.unsubscribe("proxyStateChange",this.YD,this);a.unsubscribe("remotePlayerChange",this.np,this);a.unsubscribe("remoteQueueChange",this.Zs,this);a.unsubscribe("previousNextChange",this.UD,this);a.unsubscribe("nowAutoplaying",this.PD,this);a.unsubscribe("autoplayDismissed",this.qD,this);this.qb=this.module=null};
g.k.AC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.qb.Ba)if(J8(this)){if(!b8(this.qb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.qb).Bb()?this.qb.pause():this.qb.play();break;case "control_play":this.qb.play();break;case "control_pause":this.qb.pause();break;case "control_seek":this.I.kC(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.tM=function(a){this.K.qI(a)};
g.k.IQ=function(a){this.AC("control_subtitles_set_track",g.Vb(a)?null:a)};
g.k.wF=function(){var a=this.J.getOption("captions","track");g.Vb(a)||K8(this,a)};
g.k.Dc=function(a){this.module.Dc(a,this.J.getVideoData().lengthSeconds)};
g.k.FD=function(a){if(J8(this)){this.qb.unsubscribe("remotePlayerChange",this.np,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.qb);if(b!==c.volume||a!==c.muted)this.qb.setVolume(b,a),this.N.start();this.qb.subscribe("remotePlayerChange",this.np,this)}};
g.k.rN=function(){g.Vb(this.C)||cJa(this,this.C);this.D=!1};
g.k.YD=function(a,b){this.B.stop();2===b&&this.tF()};
g.k.np=function(){if(J8(this)){this.u.stop();var a=b8(this.qb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.Td=1;break;case 1082:case 1083:this.module.Td=0;break;default:this.module.Td=-1}switch(a.playerState){case 1081:case 1:this.Ad(new g.gL(8));this.sF();break;case 1085:case 3:this.Ad(new g.gL(9));break;case 1083:case 0:this.Ad(new g.gL(2));this.I.stop();this.Dc(this.J.getVideoData().lengthSeconds);break;case 1084:this.Ad(new g.gL(4));break;case 2:this.Ad(new g.gL(4));
this.Dc(X7(a));break;case -1:this.Ad(new g.gL(64));break;case -1E3:this.Ad(new g.gL(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.qb).u;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,cJa(this,a));a=b8(this.qb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.N.isActive()||this.VF()}else bJa(this)};
g.k.UD=function(){this.J.W("mdxpreviousnextchange")};
g.k.Zs=function(){J8(this)||bJa(this)};
g.k.PD=function(a){isNaN(a)||this.J.W("mdxnowautoplaying",a)};
g.k.qD=function(){this.J.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.qb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.qb).playerState?L8(this,a):b&&this.qb.seekTo(a)};
g.k.VF=function(){if(J8(this)){var a=b8(this.qb);this.events.Ab(this.P);a.muted?this.J.mute():this.J.unMute();this.J.setVolume(a.volume);this.P=this.events.R(this.J,"onVolumeChange",this.FD)}};
g.k.sF=function(){this.u.stop();if(!this.qb.la()){var a=b8(this.qb);a.Bb()&&this.Ad(new g.gL(8));this.Dc(X7(a));this.u.start()}};
g.k.tF=function(){this.B.stop();this.u.stop();var a=this.qb.C.getReconnectTimeout();2==this.qb.Ba&&!isNaN(a)&&this.B.start()};
g.k.Ad=function(a){this.B.stop();var b=this.F;if(!g.lL(b,a)){var c=g.T(a,2);c!==g.T(this.F,2)&&g.t0(this.J.app,c);this.F=a;eJa(this.module,b,a)}};g.u(M8,g.V);M8.prototype.lc=function(){this.u.show()};
M8.prototype.Za=function(){this.u.hide()};
M8.prototype.B=function(){g.CK("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){e6("mdx-manual-pairing-popup-ok");this.Za()};g.u(N8,g.V);N8.prototype.lc=function(){this.u.show()};
N8.prototype.Za=function(){this.u.hide()};
N8.prototype.B=function(){e6("mdx-privacy-popup-cancel");this.Za()};
N8.prototype.C=function(){e6("mdx-privacy-popup-confirm");this.Za()};g.u(O8,g.V);O8.prototype.B=function(a){dJa(this,a.state)};g.u(P8,g.IZ);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.dk=g.Gb(a,this.u,this),g.JZ(this,g.Oc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.tc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.Sg=function(a){return"cast-selector-receiver"===a?"Cast...":this.dk[a].name};
P8.prototype.je=function(a){g.IZ.prototype.je.call(this,a);this.J.setOption("remote","currentReceiver",this.dk[a]);this.Ra.Za()};g.u(Q8,g.uS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.jC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script")};WIa(b,a);this.subscriptions.push(g.Mo("yt-remote-before-disconnect",this.rM,this));this.subscriptions.push(g.Mo("yt-remote-connection-change",this.rO,this));this.subscriptions.push(g.Mo("yt-remote-receiver-availability-change",this.WD,this));this.subscriptions.push(g.Mo("yt-remote-auto-connect",this.pO,this));this.subscriptions.push(g.Mo("yt-remote-receiver-resumed",
this.oO,this));this.subscriptions.push(g.Mo("mdx-privacy-popup-confirm",this.MP,this));this.subscriptions.push(g.Mo("mdx-privacy-popup-cancel",this.LP,this));this.subscriptions.push(g.Mo("mdx-manual-pairing-popup-ok",this.nJ,this));this.WD()};
g.k.load=function(){this.player.cancelPlayback();g.uS.prototype.load.call(this);this.qh=new I8(this,this.player,this.qb);var a=(a=aJa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Dc(a);eJa(this,this.xc,this.xc);g.B0(this.player.app,6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.nj=this.Pg;g.dg(this.qh,this.qb);this.qb=this.qh=null;g.uS.prototype.unload.call(this);g.B0(this.player.app,5);R8(this)};
g.k.aa=function(){g.No(this.subscriptions);g.uS.prototype.aa.call(this)};
g.k.Rh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.qh.AC.apply(this.qh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Td};
g.k.mI=function(){return this.loaded?this.qh.suggestion:null};
g.k.Eh=function(){return this.qb?b8(this.qb).Eh:!1};
g.k.hasNext=function(){return this.qb?b8(this.qb).hasNext:!1};
g.k.Dc=function(a,b){this.UB=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.UB};
g.k.getProgressState=function(){var a=b8(this.qb),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Sd():!a.isAdPlaying()&&this.player.Sd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+V7(a):a.D,isAtLiveHead:1>=(a.C?a.B+V7(a):a.B)-this.getCurrentTime(),loaded:a.P,seekableEnd:a.C?a.B+V7(a):a.B,seekableStart:0<a.F?a.F+
V7(a):a.F}};
g.k.nextVideo=function(){this.qb&&this.qb.nextVideo()};
g.k.jt=function(){this.qb&&this.qb.jt()};
g.k.rM=function(a){1===a&&(this.ox=this.qb?b8(this.qb):null)};
g.k.rO=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.nj;this.loaded&&this.unload();this.qb=a;this.ox=null;b.key!==this.Pg.key&&(this.nj=b,this.load())}else g.cg(this.qb),this.qb=null,this.loaded&&(this.unload(),(a=this.ox)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.WD=function(){this.dk=[this.Pg].concat(YIa());var a=A8()||this.Pg;S8(this,a);this.player.va("onMdxReceiversChange")};
g.k.pO=function(){var a=A8();S8(this,a)};
g.k.oO=function(){this.nj=A8()};
g.k.MP=function(){this.rp=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.LP=function(){this.rp=!1;R8(this);S8(this,this.Pg);this.nj=this.Pg;G8=!1;H8=null;this.player.playVideo()};
g.k.nJ=function(){this.ks=!0;R8(this);g.mt("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.Pd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.dk;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.nj:this.Pg;case "quickCast":return 2===this.dk.length&&"cast-selector-receiver"===this.dk[1].key?(b&&R7(),!0):!1}};
g.k.iy=function(){this.qb.iy()};
g.k.dh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nX.remote=Q8;})(_yt_player);
